include("./EnergiesTests.jl")
include("./SubspaceSolverTests.jl")
include("./GrossPitaevskiiTests.jl")
include("./PLaplacianTests.jl")
include("./SemilinearPoissonTests.jl")
include("./SolversTests.jl")
include("./iterationTest.jl")
include("./convergencetest.jl")
