# Shared one-level nonlinear-source baselines and triangular partition output.
# This remains example infrastructure: AS/RAS are comparison methods, not
# part of the VariationalDD package solver API.

const NONLINEAR_SOURCE_METHODS = (
  :nonlinear_as,
  :nonlinear_ras,
  :var_dd,
  :var_dd_history,
)

const SEMILINEAR_SOURCE_METHODS = (
  :nonlinear_as,
  :nonlinear_ras,
  :anderson_ras,
  :newton_pcg_as_4,
  :newton_pcg_as_8,
  :energy_imex_pcg_as,
  :aspin,
  :raspen,
  :var_dd,
  :var_dd_history,
)

"Work counters whose units remain separate because nonlinear and linear local solves are not equivalent."
Base.@kwdef mutable struct NonlinearSourceWork
  nonlinear_local_batches::Int = 0
  linear_as_batches::Int = 0
  global_jacobian_products::Int = 0
end

function nonlinear_source_result(u, energies, residuals, work)
  return (
    u=u,
    energy_history=energies,
    residual_history=residuals,
    nonlinear_local_batches=work.nonlinear_local_batches,
    linear_as_batches=work.linear_as_batches,
    global_jacobian_products=work.global_jacobian_products,
  )
end

"Armijo globalization for a direction generated by a comparison method."
function nonlinear_energy_line_search(energy, u, direction; c=1e-4)
  gradient = Energies.gradient(energy, u)
  slope = dot(gradient, direction)
  if !isfinite(slope) || slope >= 0
    direction = -gradient
    slope = -dot(gradient, gradient)
  end
  energy0 = Energies.energy(energy, u)
  alpha = 1.0
  while alpha >= 2.0^-30
    trial = u + alpha * direction
    if Energies.energy(energy, trial) <= energy0 + c * alpha * slope
      return trial
    end
    alpha *= 0.5
  end
  return copy(u)
end

"Additive Schwarz application assembled from the current SPD Jacobian."
function nonlinear_apply_as(factors, dofs, residual)
  result = zeros(length(residual))
  for (factor, indices) in zip(factors, dofs)
    result[indices] .+= factor \ residual[indices]
  end
  return result
end

"PCG with a fixed number of AS applications, or an accurate relative inner solve."
function nonlinear_pcg_as(
  A,
  rhs,
  dofs;
  x0=zeros(length(rhs)),
  maxiter,
  relative_tolerance=0.0,
  factors=nothing,
)
  as_factors = isnothing(factors) ?
               [cholesky(Symmetric(sparse(A[d, d]))) for d in dofs] : factors
  x = copy(x0)
  r = rhs - A * x
  initial = norm(r)
  initial == 0 && return (x=x, iterations=0, matvecs=1)
  z = nonlinear_apply_as(as_factors, dofs, r)
  p = copy(z)
  rz = dot(r, z)
  iterations = 0
  for iteration = 1:maxiter
    Ap = A * p
    denominator = dot(p, Ap)
    (!isfinite(denominator) || denominator <= 0) && break
    alpha = rz / denominator
    x .+= alpha .* p
    r .-= alpha .* Ap
    iterations = iteration
    norm(r) <= relative_tolerance * initial && break
    z = nonlinear_apply_as(as_factors, dofs, r)
    rz_new = dot(r, z)
    (!isfinite(rz_new) || rz_new <= 0) && break
    p .= z .+ (rz_new / rz) .* p
    rz = rz_new
  end
  return (x=x, iterations=iterations, matvecs=iterations + 1)
end

"The optimally damped nonlinear RAS map and its local minimizers."
function nonlinear_ras_map(energy, u, dofs, restricted_dofs)
  candidates = [Solvers.nonlinear_local_minimize(
    energy,
    u,
    indices;
    relative_tolerance=1e-11,
    absolute_tolerance=1e-12,
    maxiter=80,
  ).u for indices in dofs]
  direction = zeros(length(u))
  for i in eachindex(dofs), degree in restricted_dofs[i]
    direction[degree] = candidates[i][degree] - u[degree]
  end
  next = Solvers.minimize_affine_corrections(
    energy,
    u,
    reshape(direction, :, 1);
    relative_tolerance=1e-12,
    absolute_tolerance=1e-13,
  ).u
  return (next=next, correction=direction, candidates=candidates)
end

function nonlinear_source_schwarz_baseline(
  energy,
  subdomains;
  method,
  core_subdomains=nothing,
  u0,
  maxiter,
  tolerance,
)
  method in (:nonlinear_as, :nonlinear_ras) ||
    throw(ArgumentError("unsupported nonlinear source baseline $method"))
  dofs = [collect(Int, indices) for indices in subdomains]
  restricted_dofs = if method == :nonlinear_ras
    isnothing(core_subdomains) && throw(ArgumentError(
      "nonlinear RAS requires the nonoverlapping METIS core partition",
    ))
    FEMDiscretizations.create_balanced_disjoint_dofs_partition(
      core_subdomains, length(u0)
    )
  else
    nothing
  end

  u = copy(u0)
  energy_history = [Energies.energy(energy, u)]
  residual_history = [norm(Energies.gradient(energy, u))]
  initial_residual = residual_history[1]
  for _ = 1:maxiter
    candidates = hcat([
      Solvers.inf_step(energy, u, indices) for indices in dofs
    ]...)
    corrections = candidates .- u
    direction = if method == :nonlinear_as
      vec(sum(corrections; dims=2))
    else
      restricted = zeros(length(u))
      for i in eachindex(dofs), degree in restricted_dofs[i]
        restricted[degree] = corrections[degree, i]
      end
      restricted
    end
    u = Solvers.minimize_affine_corrections(
      energy, u, reshape(direction, :, 1)
    ).u
    push!(energy_history, Energies.energy(energy, u))
    push!(residual_history, norm(Energies.gradient(energy, u)))
    residual_history[end] <= tolerance * initial_residual && break
  end
  work = NonlinearSourceWork(
    nonlinear_local_batches=length(energy_history) - 1,
  )
  return nonlinear_source_result(u, energy_history, residual_history, work)
end

function nonlinear_source_vardd(
  energy,
  subdomains;
  u0,
  maxiter,
  tolerance,
  history_depth,
)
  initial_residual = norm(Energies.gradient(energy, u0))
  u, _, energy_history, _, residuals = Solvers.var_dd(
    energy,
    subdomains;
    u0=u0,
    maxiter=maxiter,
    tol=tolerance * initial_residual,
    history_depth=history_depth,
    verbose=false,
  )
  work = NonlinearSourceWork(
    nonlinear_local_batches=length(energy_history) - 1,
  )
  return nonlinear_source_result(
    u,
    energy_history,
    vcat(initial_residual, residuals),
    work,
  )
end

"Anderson acceleration (type II) of the optimally damped nonlinear RAS map."
function nonlinear_source_anderson_ras(
  energy,
  subdomains,
  core_subdomains;
  u0,
  maxiter,
  tolerance,
  history_depth,
)
  history_depth >= 0 || throw(ArgumentError("history_depth must be nonnegative"))
  dofs = [collect(Int, indices) for indices in subdomains]
  restricted = FEMDiscretizations.create_balanced_disjoint_dofs_partition(
    core_subdomains,
    length(u0),
  )
  u = copy(u0)
  energies = [Energies.energy(energy, u)]
  residuals = [norm(Energies.gradient(energy, u))]
  initial = residuals[1]
  iterates = Vector{Vector{Float64}}()
  fixed_point_residuals = Vector{Vector{Float64}}()
  work = NonlinearSourceWork()

  for _ = 1:maxiter
    map = nonlinear_ras_map(energy, u, dofs, restricted)
    work.nonlinear_local_batches += 1
    fixed_point_residual = map.next - u
    push!(iterates, copy(u))
    push!(fixed_point_residuals, fixed_point_residual)
    depth = min(history_depth, length(iterates) - 1)
    candidate = map.next
    if depth > 0
      first_index = length(iterates) - depth
      delta_x = hcat([
        iterates[j+1] - iterates[j] for j = first_index:length(iterates)-1
      ]...)
      delta_f = hcat([
        fixed_point_residuals[j+1] - fixed_point_residuals[j] for
        j = first_index:length(fixed_point_residuals)-1
      ]...)
      coefficients = delta_f \ fixed_point_residual
      accelerated = map.next - (delta_x + delta_f) * coefficients
      # Safeguard the multisecant extrapolation by the common energy merit
      # function. The unaccelerated nonlinear RAS step is always available.
      if all(isfinite, accelerated) &&
         Energies.energy(energy, accelerated) <= Energies.energy(energy, map.next)
        candidate = accelerated
      end
    end
    u = candidate
    push!(energies, Energies.energy(energy, u))
    push!(residuals, norm(Energies.gradient(energy, u)))
    residuals[end] <= tolerance * initial && break
  end
  return nonlinear_source_result(u, energies, residuals, work)
end

"Inexact Newton with a current-Hessian additive-Schwarz PCG solve."
function nonlinear_source_newton_pcg_as(
  energy,
  subdomains;
  u0,
  maxiter,
  tolerance,
  inner_iterations,
  inner_relative_tolerance=0.0,
)
  dofs = [collect(Int, indices) for indices in subdomains]
  u = copy(u0)
  energies = [Energies.energy(energy, u)]
  residuals = [norm(Energies.gradient(energy, u))]
  initial = residuals[1]
  work = NonlinearSourceWork()
  for _ = 1:maxiter
    gradient = Energies.gradient(energy, u)
    residuals[end] <= tolerance * initial && break
    H = Energies.hessian(energy, u)
    linear = nonlinear_pcg_as(
      H,
      -gradient,
      dofs;
      maxiter=inner_iterations,
      relative_tolerance=inner_relative_tolerance,
    )
    work.linear_as_batches += linear.iterations
    work.global_jacobian_products += linear.matvecs
    u = nonlinear_energy_line_search(energy, u, linear.x)
    push!(energies, Energies.energy(energy, u))
    push!(residuals, norm(Energies.gradient(energy, u)))
  end
  return nonlinear_source_result(u, energies, residuals, work)
end

"Spicher--Wihler stabilized IMEX iteration, with each linear step solved by PCG(AS)."
function nonlinear_source_energy_imex_pcg_as(
  energy,
  stiffness,
  mass,
  subdomains;
  u0,
  maxiter,
  tolerance,
  timestep,
  inner_maxiter,
  inner_relative_tolerance=1e-10,
)
  timestep > 0 || throw(ArgumentError("timestep must be positive"))
  dofs = [collect(Int, indices) for indices in subdomains]
  inverse_timestep = inv(timestep)
  A = stiffness + inverse_timestep * mass
  factors = [cholesky(Symmetric(sparse(A[d, d]))) for d in dofs]
  u = copy(u0)
  energies = [Energies.energy(energy, u)]
  residuals = [norm(Energies.gradient(energy, u))]
  initial = residuals[1]
  work = NonlinearSourceWork()
  for _ = 1:maxiter
    residuals[end] <= tolerance * initial && break
    gradient = Energies.gradient(energy, u)
    # K*u-gradient is the assembled reaction-plus-load vector.
    rhs = inverse_timestep * (mass * u) + stiffness * u - gradient
    linear = nonlinear_pcg_as(
      A,
      rhs,
      dofs;
      x0=u,
      maxiter=inner_maxiter,
      relative_tolerance=inner_relative_tolerance,
      factors,
    )
    work.linear_as_batches += linear.iterations
    work.global_jacobian_products += linear.matvecs
    u = linear.x
    push!(energies, Energies.energy(energy, u))
    push!(residuals, norm(Energies.gradient(energy, u)))
  end
  return nonlinear_source_result(u, energies, residuals, work)
end

"Minimal unrestarted GMRES for a matrix-free linear operator."
function nonlinear_operator_gmres(operator, rhs; maxiter, relative_tolerance)
  beta = norm(rhs)
  beta == 0 && return (x=zeros(length(rhs)), iterations=0)
  dimension = min(maxiter, length(rhs))
  V = zeros(length(rhs), dimension + 1)
  H = zeros(dimension + 1, dimension)
  V[:, 1] .= rhs ./ beta
  least_squares_rhs = zeros(dimension + 1)
  least_squares_rhs[1] = beta
  solution = zeros(length(rhs))
  for iteration = 1:dimension
    w = operator(view(V, :, iteration))
    for _ = 1:2, j = 1:iteration
      coefficient = dot(view(V, :, j), w)
      H[j, iteration] += coefficient
      w .-= coefficient .* view(V, :, j)
    end
    H[iteration+1, iteration] = norm(w)
    H[iteration+1, iteration] > eps(beta) &&
      (V[:, iteration+1] .= w ./ H[iteration+1, iteration])
    coefficients = view(H, 1:iteration+1, 1:iteration) \
                   view(least_squares_rhs, 1:iteration+1)
    solution .= view(V, :, 1:iteration) * coefficients
    residual = norm(
      view(least_squares_rhs, 1:iteration+1) -
      view(H, 1:iteration+1, 1:iteration) * coefficients,
    )
    (residual <= relative_tolerance * beta ||
     H[iteration+1, iteration] <= eps(beta)) &&
      return (x=solution, iterations=iteration)
  end
  return (x=solution, iterations=dimension)
end

"ASPIN with the classical additive nonlinear correction and approximate Jacobian."
function nonlinear_source_aspin(
  energy,
  subdomains;
  u0,
  maxiter,
  tolerance,
  inner_maxiter=40,
  inner_relative_tolerance=1e-6,
)
  dofs = [collect(Int, indices) for indices in subdomains]
  u = copy(u0)
  energies = [Energies.energy(energy, u)]
  residuals = [norm(Energies.gradient(energy, u))]
  initial = residuals[1]
  work = NonlinearSourceWork()

  for _ = 1:maxiter
    residuals[end] <= tolerance * initial && break
    candidates = [Solvers.nonlinear_local_minimize(
      energy,
      u,
      indices;
      relative_tolerance=1e-11,
      absolute_tolerance=1e-12,
      maxiter=80,
    ).u for indices in dofs]
    work.nonlinear_local_batches += 1
    correction = vec(sum(hcat(candidates...) .- u; dims=2))

    # Classical ASPIN replaces the exact derivatives at the local nonlinear
    # solutions by the current global Hessian and its overlapping blocks.
    H = Energies.hessian(energy, u)
    factors = [cholesky(Symmetric(sparse(H[d, d]))) for d in dofs]
    function approximate_jacobian_action(vector)
      Hvector = H * vector
      output = zeros(length(u))
      for (indices, factor) in zip(dofs, factors)
        output[indices] .-= factor \ Hvector[indices]
      end
      return output
    end
    linear = nonlinear_operator_gmres(
      approximate_jacobian_action,
      -correction;
      maxiter=inner_maxiter,
      relative_tolerance=inner_relative_tolerance,
    )
    work.linear_as_batches += linear.iterations
    work.global_jacobian_products += linear.iterations
    u = nonlinear_energy_line_search(energy, u, linear.x)
    push!(energies, Energies.energy(energy, u))
    push!(residuals, norm(Energies.gradient(energy, u)))
  end
  return nonlinear_source_result(u, energies, residuals, work)
end

"RASPEN: Newton applied to the restricted nonlinear Schwarz correction."
function nonlinear_source_raspen(
  energy,
  subdomains,
  core_subdomains;
  u0,
  maxiter,
  tolerance,
  inner_maxiter=40,
  inner_relative_tolerance=1e-6,
)
  dofs = [collect(Int, indices) for indices in subdomains]
  restricted = FEMDiscretizations.create_balanced_disjoint_dofs_partition(
    core_subdomains,
    length(u0),
  )
  positions = [Dict(degree => position for (position, degree) in pairs(d)) for d in dofs]
  u = copy(u0)
  energies = [Energies.energy(energy, u)]
  residuals = [norm(Energies.gradient(energy, u))]
  initial = residuals[1]
  work = NonlinearSourceWork()

  for _ = 1:maxiter
    residuals[end] <= tolerance * initial && break
    map = nonlinear_ras_map(energy, u, dofs, restricted)
    work.nonlinear_local_batches += 1
    local_hessians = [Energies.hessian(energy, candidate) for candidate in map.candidates]
    local_factors = [
      cholesky(Symmetric(sparse(H[d, d]))) for (H, d) in zip(local_hessians, dofs)
    ]
    function jacobian_action(vector)
      output = zeros(length(u))
      for i in eachindex(dofs)
        indices = dofs[i]
        local_derivative = -(
          local_factors[i] \ (local_hessians[i] * vector)[indices]
        )
        for degree in restricted[i]
          output[degree] = local_derivative[positions[i][degree]]
        end
      end
      return output
    end
    linear = nonlinear_operator_gmres(
      jacobian_action,
      -map.correction;
      maxiter=inner_maxiter,
      relative_tolerance=inner_relative_tolerance,
    )
    work.linear_as_batches += linear.iterations
    work.global_jacobian_products += length(dofs) * linear.iterations
    u = nonlinear_energy_line_search(energy, u, linear.x)
    push!(energies, Energies.energy(energy, u))
    push!(residuals, norm(Energies.gradient(energy, u)))
  end
  return nonlinear_source_result(u, energies, residuals, work)
end

function triangle_partition_rows(N, ms, overlap)
  rows = (
    m=Int[], N=Int[], idx=Int[], owner=Int[], mult=Int[],
    x1=Float64[], y1=Float64[], x2=Float64[], y2=Float64[],
    x3=Float64[], y3=Float64[],
  )
  model = simplexify(CartesianDiscreteModel(
    (0, 1.0, 0, 1.0), (N, N); isperiodic=(false, false)
  ))
  coordinates = get_cell_coordinates(Triangulation(model))
  graph = GridapDistributed.compute_cell_graph(model, 1)
  for m in ms
    owner = Int.(Metis.partition(graph, m))
    element_partition = FEMDiscretizations.create_elements_partition(
      Int32.(owner), m
    )
    FEMDiscretizations.create_overlapping_elements_partition!(
      element_partition, graph, m, overlap
    )
    mult = zeros(Int, length(owner))
    for elements in element_partition, element in elements
      mult[element] += 1
    end
    for index in eachindex(owner)
      points = coordinates[index]
      push!(rows.m, m)
      push!(rows.N, N)
      push!(rows.idx, index)
      push!(rows.owner, owner[index])
      push!(rows.mult, mult[index])
      push!(rows.x1, points[1][1])
      push!(rows.y1, points[1][2])
      push!(rows.x2, points[2][1])
      push!(rows.y2, points[2][2])
      push!(rows.x3, points[3][1])
      push!(rows.y3, points[3][2])
    end
  end
  return rows
end
