# Regenerate the only table included in the final paper.

using CSV

const TABLES_PAPER_DIR = @__DIR__
const TABLES_DATA_DIR = joinpath(TABLES_PAPER_DIR, "data")
const TABLE_DIR = joinpath(TABLES_PAPER_DIR, "tables")
const GENERATED_TABLE_FILES = (
  "fig18_poisson_scaling.csv",
  "fig18_poisson_scaling.tex",
)

function terminal_batches(rows; experiment, regime, method, parameter, value)
  matches = filter(rows) do row
    row.experiment == experiment && row.regime == regime &&
      row.method == method && getproperty(row, parameter) == value
  end
  isempty(matches) && error(
    "missing scaling data for ($experiment, $regime, $method, $parameter=$value)"
  )
  terminal = argmax(row -> row.local_batches, matches)
  terminal.relative_residual <= 1e-10 || error(
    "curve did not reach the requested tolerance: " *
    "$(terminal.relative_residual) > 1e-10"
  )
  return terminal.local_batches
end

function make_fig18_table(;
  output_dir=TABLE_DIR,
  data_file=joinpath(TABLES_DATA_DIR, "study8_sensitivity.csv"),
)
  isfile(data_file) || error(
    "missing $data_file; run study8_linear_sensitivity.jl first"
  )
  mkpath(output_dir)
  rows = collect(CSV.File(data_file))
  methods = (
    ("\\(\\mathrm{EMDD}\\;(q=1)\\)", "var_dd_additive"),
    ("\\(\\mathrm{EMDD}\\;(q=2)\\)", "var_dd_additive_history"),
    ("\\(\\mathrm{EMDD}\\;(q=3)\\)", "emdd_q3"),
    ("\\(\\mathrm{EMDD}\\;(q=4)\\)", "emdd_q4"),
    ("\\(\\mathrm{CG{+}AS}\\)", "pcg_as"),
    ("\\(\\mathrm{GMRES{+}RAS}\\)", "gmres_ras"),
  )
  mesh_sizes = (20, 40, 60, 80, 100, 120)
  overlaps = (1, 2, 4, 8)
  columns = Dict{Symbol,Vector{String}}(:method => String[])
  for N in mesh_sizes
    columns[Symbol("fixed_layers_h$N")] = String[]
    columns[Symbol("fixed_ratio_h$N")] = String[]
  end
  for overlap in overlaps
    columns[Symbol("overlap$overlap")] = String[]
  end
  for (label, method) in methods
    push!(columns[:method], label)
    for N in mesh_sizes
      push!(columns[Symbol("fixed_layers_h$N")], string(terminal_batches(
        rows; experiment="mesh", regime="fixed_layers", method,
        parameter=:N, value=N,
      )))
      push!(columns[Symbol("fixed_ratio_h$N")], string(terminal_batches(
        rows; experiment="mesh", regime="fixed_delta_over_H", method,
        parameter=:N, value=N,
      )))
    end
    for overlap in overlaps
      push!(columns[Symbol("overlap$overlap")], string(terminal_batches(
        rows; experiment="overlap", regime="layer_sweep", method,
        parameter=:overlap, value=overlap,
      )))
    end
  end
  ordered = (;
    method=columns[:method],
    (Symbol("fixed_layers_h$N") => columns[Symbol("fixed_layers_h$N")]
      for N in mesh_sizes)...,
    (Symbol("fixed_ratio_h$N") => columns[Symbol("fixed_ratio_h$N")]
      for N in mesh_sizes)...,
    (Symbol("overlap$overlap") => columns[Symbol("overlap$overlap")]
      for overlap in overlaps)...,
  )
  CSV.write(joinpath(output_dir, GENERATED_TABLE_FILES[1]), ordered)
  latex = raw"""% Generated by examples/paper/tables_all.jl; do not edit by hand.
% Requires booktabs, graphicx, and pgfplotstable.
\providecommand{\varddtablepath}{./examples/paper/tables}
\begin{table*}[t]
  \footnotesize
  \centering
  \caption{%
    Parallel local-solve batches required to reduce the relative residual below
    \(10^{-10}\) for the Poisson problem. The first two column groups refine
    the mesh for \(m=4\); the third varies the overlap for \(1/h=64\) and
    \(m=4\). Here \(q\) denotes the EMDD history-space dimension.
  }
  \label{tab:poisson-scaling}
  \resizebox{\textwidth}{!}{%
  \pgfplotstabletypeset[
    col sep=comma,
    columns={method,fixed_layers_h20,fixed_layers_h40,fixed_layers_h60,
      fixed_layers_h80,fixed_layers_h100,fixed_layers_h120,
      fixed_ratio_h20,fixed_ratio_h40,fixed_ratio_h60,fixed_ratio_h80,
      fixed_ratio_h100,fixed_ratio_h120,overlap1,overlap2,overlap4,overlap8},
    every head row/.style={
      output empty row,
      before row={
        \toprule
        & \multicolumn{6}{c}{\makebox[0pt]{discretization \(1/h\) (\(\ell=2\))}}
        & \multicolumn{6}{c}{\makebox[0pt]{discretization \(1/h\) (\(\delta/H\approx0.1\))}}
        & \multicolumn{4}{c}{\makebox[0pt]{layers \(\ell\) (\(1/h=64\))}} \\
        \cmidrule(lr){2-7} \cmidrule(lr){8-13} \cmidrule(lr){14-17}
        method & 20 & 40 & 60 & 80 & 100 & 120
        & 20 & 40 & 60 & 80 & 100 & 120 & 1 & 2 & 4 & 8 \\
      },
      after row=\midrule
    },
    every last row/.style={after row=\bottomrule},
    every column/.style={string type,column type={r}},
    columns/method/.style={string type,column type={l@{\hspace{1em}}}},
  ]{\varddtablepath/fig18_poisson_scaling.csv}%
  }
\end{table*}
"""
  write(joinpath(output_dir, GENERATED_TABLE_FILES[2]), latex)
  println("saved tables/fig18_poisson_scaling.{csv,tex}")
end

function check_generated_tables(;
  data_file=joinpath(TABLES_DATA_DIR, "study8_sensitivity.csv"),
  committed_dir=TABLE_DIR,
)
  stale = String[]
  mktempdir() do temporary_dir
    make_fig18_table(; output_dir=temporary_dir, data_file)
    for name in GENERATED_TABLE_FILES
      generated = joinpath(temporary_dir, name)
      committed = joinpath(committed_dir, name)
      (!isfile(committed) || read(generated) != read(committed)) && push!(stale, name)
    end
  end
  isempty(stale) || error(
    "generated paper tables are stale: $(join(stale, ", "))"
  )
  println("generated paper tables are up to date")
end

function main(args=ARGS)
  isempty(args) ? make_fig18_table() :
  args == ["--check"] ? check_generated_tables() :
  error("usage: julia --project=. examples/paper/tables_all.jl [--check]")
end

abspath(PROGRAM_FILE) == abspath(@__FILE__) && main()
