# Regenerates the LaTeX tables for the paper from data/*.csv (no solves).
# Run: julia --project=. examples/paper/tables_all.jl

using CSV

const TABLES_PAPER_DIR = @__DIR__
const TABLES_DATA_DIR = joinpath(TABLES_PAPER_DIR, "data")
const TABLE_DIR = mkpath(joinpath(TABLES_PAPER_DIR, "tables"))

"Return the terminal parallel local-solve batch count for one Figure 18 curve."
function fig18_terminal_batches(rows; experiment, regime, method, parameter, value)
  matches = filter(rows) do row
    row.experiment == experiment &&
      row.regime == regime &&
      row.method == method &&
      getproperty(row, parameter) == value
  end
  isempty(matches) && error(
    "missing Figure 18 data for " *
    "($experiment, $regime, $method, $parameter=$value)",
  )
  terminal = argmax(row -> row.local_batches, matches)
  terminal.relative_residual <= 1e-10 || error(
    "Figure 18 curve did not reach the requested tolerance: " *
    "($(terminal.relative_residual) > 1e-10)",
  )
  return terminal.local_batches
end

function make_fig18_table()
  rows = collect(CSV.File(joinpath(TABLES_DATA_DIR, "study8_sensitivity.csv")))
  methods = (
    ("\\(\\mathrm{EMDD}\\;(q=1)\\)", "var_dd_additive"),
    ("\\(\\mathrm{EMDD}\\;(q=2)\\)", "var_dd_additive_history"),
    ("\\(\\mathrm{CG{+}AS}\\)", "pcg_as"),
    ("\\(\\mathrm{GMRES{+}RAS}\\)", "gmres_ras"),
  )
  mesh_sizes = (20, 40, 60, 80, 100, 120)
  overlap_layers = (1, 2, 4, 8)

  columns = Dict{Symbol,Vector{String}}(:method => String[])
  for N in mesh_sizes
    columns[Symbol("fixed_layers_h$N")] = String[]
    columns[Symbol("fixed_ratio_h$N")] = String[]
  end
  for overlap in overlap_layers
    columns[Symbol("overlap$overlap")] = String[]
  end

  for (label, method) in methods
    push!(columns[:method], label)
    for N in mesh_sizes
      fixed_layers = fig18_terminal_batches(
        rows;
        experiment="mesh",
        regime="fixed_layers",
        method,
        parameter=:N,
        value=N,
      )
      fixed_ratio = fig18_terminal_batches(
        rows;
        experiment="mesh",
        regime="fixed_delta_over_H",
        method,
        parameter=:N,
        value=N,
      )
      push!(columns[Symbol("fixed_layers_h$N")], string(fixed_layers))
      push!(columns[Symbol("fixed_ratio_h$N")], string(fixed_ratio))
    end
    for overlap in overlap_layers
      batches = fig18_terminal_batches(
        rows;
        experiment="overlap",
        regime="layer_sweep",
        method,
        parameter=:overlap,
        value=overlap,
      )
      push!(columns[Symbol("overlap$overlap")], string(batches))
    end
  end

  ordered = (; method=columns[:method],
    (Symbol("fixed_layers_h$N") => columns[Symbol("fixed_layers_h$N")]
      for N in mesh_sizes)...,
    (Symbol("fixed_ratio_h$N") => columns[Symbol("fixed_ratio_h$N")]
      for N in mesh_sizes)...,
    (Symbol("overlap$overlap") => columns[Symbol("overlap$overlap")]
      for overlap in overlap_layers)...,
  )
  data_name = "fig18_poisson_scaling.csv"
  CSV.write(joinpath(TABLE_DIR, data_name), ordered)

  latex = raw"""% Generated by examples/paper/tables_all.jl; do not edit by hand.
% Requires booktabs, graphicx, and pgfplotstable.
% Override \varddtablepath before inputting this file if the table data live
% somewhere else relative to the main LaTeX document.
\providecommand{\varddtablepath}{./examples/paper/tables}
\begin{table*}[t]
  \footnotesize
  \centering
  \caption{%
    Parallel local-solve batches required to reduce the relative residual below
    \(10^{-10}\) for the Poisson problem in Figure~18. The first two column
    groups refine the mesh for \(m=4\); the third varies the overlap for
    \(1/h=64\) and \(m=4\). Here \(q\) denotes the EMDD history-space dimension.
  }
  \label{tab:poisson-scaling}
  \resizebox{\textwidth}{!}{%
  \pgfplotstabletypeset[
    col sep=comma,
    columns={method,fixed_layers_h20,fixed_layers_h40,fixed_layers_h60,
      fixed_layers_h80,fixed_layers_h100,fixed_layers_h120,
      fixed_ratio_h20,fixed_ratio_h40,fixed_ratio_h60,fixed_ratio_h80,
      fixed_ratio_h100,fixed_ratio_h120,overlap1,overlap2,overlap4,overlap8},
    every head row/.style={
      output empty row,
      before row={
        \toprule
        & \multicolumn{6}{c}{\makebox[0pt]{fixed \(\ell=2\)}}
        & \multicolumn{6}{c}{\makebox[0pt]{fixed \(\delta/H\approx0.1\)}}
        & \multicolumn{4}{c}{\makebox[0pt]{overlap sweep}} \\
        \cmidrule(lr){2-7} \cmidrule(lr){8-13} \cmidrule(lr){14-17}
        method
        & \multicolumn{6}{c}{\makebox[0pt]{elements per direction, \(1/h\)}}
        & \multicolumn{6}{c}{\makebox[0pt]{elements per direction, \(1/h\)}}
        & \multicolumn{4}{c}{\makebox[0pt]{overlap layers, \(\ell\) (\(1/h=64\))}} \\
        \cmidrule(lr){2-7} \cmidrule(lr){8-13} \cmidrule(lr){14-17}
        & 20 & 40 & 60 & 80 & 100 & 120
        & 20 & 40 & 60 & 80 & 100 & 120
        & 1 & 2 & 4 & 8 \\
      },
      after row=\midrule
    },
    every last row/.style={after row=\bottomrule},
    every column/.style={string type,column type={r}},
    columns/method/.style={string type,column type={l@{\hspace{1em}}}},
  ]{\varddtablepath/fig18_poisson_scaling.csv}%
  }
\end{table*}
"""
  write(joinpath(TABLE_DIR, "fig18_poisson_scaling.tex"), latex)
  println("saved tables/fig18_poisson_scaling.{csv,tex}")
  return nothing
end

make_fig18_table()
