name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v4
        with:
          version: '1' # Set `version` to '1.0.54' if you need to use JuliaFormatter.jl v1.0.54 (default: '1')
          suggestion-label: 'format-suggest' # leave this unset or empty to show suggestions for all PRs
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v2
      with:
        version: '1'
    - name: Install JuliaFormatter app
      run: |
        julia -e 'import Pkg; Pkg.add("JuliaFormatter"); Pkg.instantiate()'
        julia -e 'import Pkg; Pkg.activate(); Pkg.build()' # optional
    - name: Check formatting
      run: |
        jlfmt --check -v src/ test/ examples/
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
    - uses: julia-actions/cache@v2
    - uses: julia-actions/julia-buildpkg@v1
    - uses: julia-actions/julia-runtest@v1
