name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v2
      with:
        version: '1'
    - name: Install JuliaFormatter app
      run: |
        julia -e 'import Pkg; Pkg.add("JuliaFormatter"); Pkg.instantiate()'
        julia -e 'import Pkg; Pkg.activate(); Pkg.build()' # optional
    - name: Check formatting
      run: |
        jlfmt --check -v src/ test/ examples/
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
    - uses: julia-actions/cache@v2
    - uses: julia-actions/julia-buildpkg@v1
    - uses: julia-actions/julia-runtest@v1
